version: "2.1"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka1:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS:
        "INTERNAL://kafka1:9090,\
         A://:9092"
      KAFKA_ADVERTISED_LISTENERS:
        "INTERNAL://kafka1:9090,\
         A://192.168.99.100:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP:
        "INTERNAL:PLAINTEXT,\
         A:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
   volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka2:
    image: wurstmeister/kafka
    ports:
      - "9093:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENERS:
        "INTERNAL://kafka2:9090,\
         A://:9093"
      KAFKA_ADVERTISED_LISTENERS:
        "INTERNAL://kafka2:9090,\
         A://192.168.99.100:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP:
        "INTERNAL:PLAINTEXT,\
         A:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
   volumes:
      - /var/run/docker.sock:/var/run/docker.sock